### ISSUE TITLE
IPINFO_TOKEN env variable support to use with defaultScrapersWithOptions

### ISSUE THREAD

**Issue by dwisiswant0** [projectdiscovery/cdncheck#14]
While I was doing my PR #13, I was testing whether the CIDR was really scraped or not.
Apparently, there are several providers that do not produce CIDRs, those are Akamai & Sucuri.
![Screenshot_2021-02-24_01-14-10](https://user-images.githubusercontent.com/25837540/108889765-53731400-763f-11eb-8976-0fc89782f550.png)

Then I checked where the CIDR resource for that provider is hit the endpoint, and it comes from `ipinfo.io`. Then I tried to hit via cURL, but it resulted in an error with a message: required access token.
![Screenshot_2021-02-24_01-22-55](https://user-images.githubusercontent.com/25837540/108889829-65ed4d80-763f-11eb-95f6-dfdeee32c9e8.png)

The conclusion is, to get the CIDR resource from `ipinfo.io` an access token is required. Are there any other resources to get the CIDR range for those provider? Or it just me who missed it? But I'm not sure, since the `scrape...` function itself doesn't returning an error if CIDR slice is less than 1.

**Comment by gabemarshall** [comment]
@dwisiswant0 What about using whois rather than ipinfo.io? I did a quick check against AS30148 and the resulting data is basically the same.

`whois -h whois.radb.net -- '-i origin AS30148' | grep 'route'`

...

```
route:      193.19.225.0/24
route:      192.124.249.0/24
route:      192.88.134.0/23
route:      185.93.228.0/22
route:      66.248.200.0/22
route:      208.109.0.0/22
route:          185.93.231.0/24
route:          192.124.249.0/24
route:          192.161.0.0/24
route:          193.19.224.0/22
route6:     2a02:fe80::/29
route6:     2a02:fe80:1010::/48
route6:     2a02:fe80:2010::/48
route6:         2a02:fe80:16::/48
route6:         2a02:fe80:1010::/48
route6:         2a02:fe80:2010::/48
```

**Comment by ehsandeep** [comment]
This is now fixed in the dev version. Now client reads `IPINFO_TOKEN` as ENV variable.

**Comment by dwisiswant0** [comment]
Nice!
