### ISSUE TITLE
Add Google / Oracle CDN source

### ISSUE THREAD

**Issue by yassineaboukir** [projectdiscovery/cdncheck#20]
Hi,

You can also add Google CDN IP ranges which are published on their officially updated endpoint:

>https://www.gstatic.com/ipranges/cloud.json

Regards.

**Comment by ehsandeep** [comment]
For Oracle:

```
curl -sL https://docs.oracle.com/iaas/tools/public_ip_ranges.json | jq -r '.regions[].cidrs[].cidr'
```

**Comment by ehsandeep** [comment]
@yassineaboukir, this is now supported.
