### ISSUE TITLE
Request to Cut a New Tag for Updated Dependencies

### ISSUE THREAD

**Issue by Tyler-Staut** [projectdiscovery/cdncheck#273]
I am currently using Nuclei and I have encountered an issue with the `github.com/mholt/archiver` dependency. The current tagged release includes version `v3.1.1+incompatible`. The issue has been addressed in the main branch with version `v3.5.1`

**Comment by ehsandeep** [comment]
https://github.com/projectdiscovery/cdncheck/releases/tag/v1.0.11
