### ISSUE TITLE
IP Mapping Error

### ISSUE THREAD

**Issue by PR3R00T** [projectdiscovery/cdncheck#312]
Passing in a subdomain Im expecting a DNS lookup for the IP to check if its on a CDN network. This IP I believe should be mapped to the IP json field, its not currently on the latest.

![image](https://github.com/user-attachments/assets/ff55f877-517d-4799-9970-47409635e3c4)

**Comment by dogancanbakir** [comment]
@PR3R00T Could you share repro steps (cmd)?

**Comment by PR3R00T** [comment]
Echo google.com|cdncheck -j
