### ISSUE TITLE
Add StackPath as source

### ISSUE THREAD

**Issue by edoardottt** [projectdiscovery/cdncheck#51]
[StackPath](https://www.stackpath.com/) can be used as source for IP CDN checking. Since there is no public available list of IP addresses / CIDR ranges, ip.info can be used with AS [AS64259](https://ipinfo.io/AS64259).

I would update by myself the json, but I'm on the Free plan and fetching ASN with APIs requires at least a Basic Plan.

**Comment by neonbunny** [comment]
StackPath consists of more than just that one ASN - I have therefore swapped it for a file linked to from their support docs - see #88
