### ISSUE TITLE
Can I submit a PR that adds cloud providers like Amazon and Digital Ocean?

### ISSUE THREAD

**Issue by TheTechromancer** [projectdiscovery/cdncheck#57]
Thanks for making this repo; it's very useful! My question is, since I often need to detect whether an IP belongs to a cloud provider, and not strictly a CDN, would you accept a PR which adds cloud providers such as those listed [here](https://github.com/nccgroup/cloud_ip_ranges)? Or is the scope of this repo restricted to CDNs only?

After this change, you could use cdncheck to detect whether an IP belonged to a cloud provider, e.g. give it the IP of an s3 bucket and it would return "amazon". Curious about your thoughts.

**Comment by ehsandeep** [comment]
@TheTechromancer yes you can add cloud providers and here are details - https://github.com/projectdiscovery/cdncheck#how-to-add-new-providers
