### ISSUE TITLE
Include CheckSuffix check

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/cdncheck#80]
https://github.com/projectdiscovery/cdncheck/blob/dev/other.go#L22

```
Would be great to include CheckSuffix function ( https://github.com/projectdiscovery/cdncheck/blob/dev/other.go#L22 ) and CheckWappalyzer as fallback as well
```
_Originally posted by @brenocss in https://github.com/projectdiscovery/cdncheck/issues/67#issuecomment-1521963175_

**Comment by brenocss** [comment]
This is useful in cases like akamai

```zsh
echo www.gap.com | cdncheck

            __           __              __
  _________/ /___  _____/ /_  ___  _____/ /__
 / ___/ __  / __ \/ ___/ __ \/ _ \/ ___/ //_/
/ /__/ /_/ / / / / /__/ / / /  __/ /__/ ,<
\___/\__,_/_/ /_/\___/_/ /_/\___/\___/_/|_|

                projectdiscovery.io

[INF] No results found.
```

```zsh
echo www.gap.com | whatcdn -json | jq
{
  "input": "www.gap.com",
  "input_type": "domain",
  "ips": [
    "104.87.29.118"
  ],
  "cnames": [
    "www.gap.com.edgekey.net",
    "e12405.x.akamaiedge.net"
  ],
  "hasInternalIps": false,
  "hasCDN": true,
  "detectedCDNs": [
    {
      "name": "akamai",
      "DetectionMethod": "cname",
      "DetectedPTRDomains": [
        "www.gap.com.edgekey.net"
      ]
    }
  ],
  "hasWaf": false,
  "hasCloud": false
}
```

**Comment by tarunKoyalwar** [comment]
@brenocss seems to be working on this issue

**Comment by brenocss** [comment]
https://github.com/projectdiscovery/cdncheck/pull/86 

![image](https://user-images.githubusercontent.com/57222005/235268184-7527b20f-e724-4fbc-973b-90ac42679503.png)

**Comment by brenocss** [comment]
@ehsandeep @tarunKoyalwar  Do you think it would be a good idea to include checks for type AAAA and to verify additional IP addresses in type A responses?

For now we just check 1 IP in type A response

https://github.com/projectdiscovery/cdncheck/blob/41a8e9b337ddeb9f586a011072383570ccb6642f/internal/runner/runner.go#L277

If that's the case, I can also add this check to my branch. ( In my branch I add a check for a list of Ips )

https://github.com/projectdiscovery/cdncheck/blob/bbabe7041c098db33e21f6cece7e823cc8a67aa7/cdncheck.go#L109
